/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-04-01 13:09:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.mysql.cj.xdevapi.PreparableStatement;
import java.util.*;
import java.text.*;
import java.sql.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/kma/pro01/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/test01/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1711948367981L));
    _jspx_dependants.put("jar:file:/D:/kma/pro01/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/test01/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("com.mysql.cj.xdevapi.PreparableStatement");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("utf-8");
	response.setCharacterEncoding("utf-8");
	response.setContentType("text/html; charset=utf-8");
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>메뉴 연습</title>\r\n");
      out.write("    <style>\r\n");
      out.write("    * { margin: 0; padding: 0; }\r\n");
      out.write("    ul { list-style: none; }\r\n");
      out.write("    a { text-decoration: none; color:#333; }\r\n");
      out.write("    #gnb { width:1400px; margin: 20px auto; }\r\n");
      out.write("    #gnb > ul > li { float:left; width: 200px; }\r\n");
      out.write("    #gnb > ul > li > a { font-size:20px; font-weight: bold; \r\n");
      out.write("    display:block; text-align: center; line-height: 42px; border-bottom:3px solid #333; }\r\n");
      out.write("    #gnb > ul > li > ul { display:none; }\r\n");
      out.write("    #gnb > ul > li:hover > ul { display:block; }\r\n");
      out.write("    #gnb ul li a { display:block; text-align: center; line-height: 32px; }\r\n");
      out.write("    #gnb > ul > li:hover > a { color:deepskyblue;  border-bottom:3px solid deepskyblue; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<ul>\r\n");
      out.write("        <h1 style=\"text-align: center;\">풍남동</h1>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <nav id=\"gnb\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"\">풍남동 소개</a>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"introduce.jsp\">풍남동을 소개합니다. </a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"\">문화 유적</a>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"CulturalRelics_ggj.jsp\">경기전 </a></li>\r\n");
      out.write("                    <li><a href=\"CulturalRelics_jlgy.jsp\">전라감영 </a></li>\r\n");
      out.write("                    <li><a href=\"CulturalRelics_jdcc.jsp\">전동성당 </a></li>\r\n");
      out.write("                    <li><a href=\"CulturalRelics_pnm.jsp\">풍남문 </a></li>\r\n");
      out.write("                    <li><a href=\"CulturalRelics_omd.jsp\">오목대 </a></li>\r\n");
      out.write("                    <li><a href=\"CulturalRelics_hg.jsp\">향교</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"\">문화 시설</a>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"CulturalFacility_ka.jsp\">강암서예관 </a></li>\r\n");
      out.write("                    <li><a href=\"CulturalFacility_cmh.jsp\">최명희문학관 </a></li>\r\n");
      out.write("                    <li><a href=\"CulturalFacility_hv.jsp\">전주한목마을 역사관</a></li>\r\n");
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"\">공연,전시시설</a>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"Exhibition_ah.jsp\">전북예술회관  </a></li>\r\n");
      out.write("                    <li><a href=\"Exhibition_hb.jsp\">한벽문화관  </a></li>\r\n");
      out.write("                    <li><a href=\"Exhibition_st.jsp\">창작소극장 </a></li>\r\n");
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"\">체험 정보</a>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"Experience_hb.jsp\">한복체험</a></li>\r\n");
      out.write("                    <li><a href=\"Experience_craft.jsp\">전통공예</a></li>\r\n");
      out.write("                    <li><a href=\"Experience_tgame.jsp\">전통놀이 체험</a></li>\r\n");
      out.write("                    <li><a href=\"Experience_mannrer.jsp\">예절체험</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"\">교육 컨텐츠</a>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"Education_cu.jsp\">청을전통 문화원</a></li>\r\n");
      out.write("                    <li><a href=\"Education_pan.jsp\">판소리/민요/풍물 배우기</a></li>\r\n");
      out.write("                    <li><a href=\"Education_dan.jsp\">전통춤 배우기</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"\">기타 정보</a>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"Other_at.jsp\">풍남동 편의시설 정보</a></li>\r\n");
      out.write("                    <li><a href=\"Other_car.jsp\">공유 운송차 '다가온'</a></li>\r\n");
      out.write("                    <li><a href=\"Other_parking.jsp\">주차 시설</a></li>\r\n");
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<nav>\r\n");
      out.write("    <div class=\"img1\" style=\"width: 500px;  margin-right: auto; margin-left: auto; margin-top:300px; \" >\r\n");
      out.write("		<h3></h3>\r\n");
      out.write("        \r\n");
      out.write("		<img src=\"img01/한옥마을.jpg\" alt=\"\" class=\"img1\"/>\r\n");
      out.write("	</div>\r\n");
      out.write("    </nav> \r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
